[package]
name = "single_cell_toolkit"
version = "0.2.0"
authors = ["Gert Hulselmans <gert.hulselmans@kuleuven.be>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.7"
bio-types = "1.0"
clap = { version = "4.4.18", features = ["derive"] }
csv = "1.3.0"
grep-cli = "0.1.10"
hashbrown = "0.14.3"
itertools = "0.12"
itoa = "1.0"
libz-sys = { version = "1.1.14", default = false, features = ["zlib-ng", "static"] }
needletail = "0.5.1"
rayon = "1.8"
rust-htslib = { version = "*", default-features = true, features = ["bzip2", "lzma", "curl", "libdeflate"] }
serde = { version = "1", features = ["derive"] }
termcolor = "1.4.1"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
