[package]
name = "single_cell_toolkit"
version = "0.1.0"
authors = ["Gert Hulselmans <gert.hulselmans@kuleuven.be>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { version = "*", default-features = true, features = ["bzip2", "lzma", "curl", "libdeflate"]  }
bio-types = "1.0"
itoa = "1.0"
grep-cli = "0.1.9"
termcolor = "1.2.0"
libz-sys = { version = "1.1.12", default = false, features = ["zlib-ng", "static"] }
needletail = "0.5.1"
rayon = "1.7"
csv = "1.2.2"
serde = { version = "1", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
